version: "3.8"

services:
  app:
    build: ./
    restart: always
    ports:
      - "8070:8070"
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
